# Generated by Django 3.2.6 on 2022-04-23 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DockStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=200)),
                ('postcode', models.CharField(max_length=100)),
                ('landmark', models.TextField(blank=True)),
                ('image', models.CharField(max_length=500, null=True)),
                ('total_docks', models.IntegerField()),
                ('bikes_availible', models.IntegerField()),
                ('dropoff_docks', models.IntegerField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_st', models.DateTimeField(auto_now=True)),
                ('otp', models.PositiveSmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
