# Generated by Django 4.0.3 on 2022-04-13 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dockstation',
            old_name='narest_landmark',
            new_name='landmark',
        ),
    ]
