# Generated by Django 3.2.6 on 2022-04-24 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20220424_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_postcode', models.CharField(max_length=20)),
                ('Charges', models.FloatField()),
                ('booking_from', models.TextField()),
                ('booking_to', models.TextField()),
                ('booking_time', models.TimeField()),
                ('leave_time', models.TimeField()),
                ('bicycle', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('user_address', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
