# Generated by Django 3.2.6 on 2022-04-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bicycle_drop_status',
            field=models.BooleanField(default=False),
        ),
    ]
