# Generated by Django 3.2.6 on 2022-04-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_booking_bicycle_drop_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='drop_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
